
export const INCREMENT_DATE = 'INCREMENT_DATE';
export const DECREMENT_DATE = 'DECREMENT_DATE';
export const SELECT_TODAY = 'SELECT_TODAY';
export const VIEW_CHANGED_EVENT = 'VIEW_CHANGED_EVENT';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';
export const CONFIGURE_CALENDAR = 'CONFIGURE_CALENDAR';
export const SELECT_TASK= 'SELECT_TASK';
export const SELECT_SLOT = 'SELECT_SLOT';
export const RETRIEVE_DATA = 'RETRIEVE_DATA';
export const OPEN_SPACE_CLICKED = 'OPEN_SPACE_CLICKED';
export const TASK_CLICKED = 'TASK_CLICKED';

export const RETRIEVE_DATA_REQUEST = 'RETRIEVE_DATA_REQUEST';
export const RETRIEVE_DATA_FAILURE = 'RETRIEVE_DATA_FAILURE';
export const RETRIEVE_DATA_SUCCESS = 'RETRIEVE_DATA_SUCCESS';
