

export const INCREMENT_MONTH = 'INCREMENT_MONTH';
export const DECREMENT_MONTH = 'DECREMENT_MONTH';
export const SELECT_TODAY = 'SELECT_TODAY';
export const SELECT_DAY = 'SELECT_DAY';
export const SELECT_DAY = 'SELECT_DAY';
export const VIEW_CHANGED_EVENT = 'VIEW_CHANGED_EVENT';
