

export const INCREMENT_DATE = 'INCREMENT_DATE';
export const DECREMENT_DATE = 'DECREMENT_DATE';
export const SELECT_TODAY = 'SELECT_TODAY';
export const SELECT_DAY = 'SELECT_DAY';
export const VIEW_CHANGED_EVENT = 'VIEW_CHANGED_EVENT';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
